apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: w9nstgvq9-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a4e40d2101.0lma.p3.openshiftapps.com/rhtap/rhtap-qe:b4873fe1cfa2d18d1fbea4d9c3a82b41bd99d38a@sha256:a0cbfb832f12e9a31f5f51bd4dc47ffcd62008cf2e62b5ce4498bc6e3f074000
        name: container-image  
